# Cloud Build configuration for ${service_name}
# Auto-generated by Terraform - Do not edit manually
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${region}-docker.pkg.dev/${project_id}/june/${service_name}:$$SHORT_SHA'
      - '-t'
      - '${region}-docker.pkg.dev/${project_id}/june/${service_name}:latest'
      - '-f'
      - 'June/services/${service_key}/Dockerfile'
      - 'June/services/${service_key}'
    timeout: '${build_timeout}'

  # Push with SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${region}-docker.pkg.dev/${project_id}/june/${service_name}:$$SHORT_SHA'

  # Push with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${region}-docker.pkg.dev/${project_id}/june/${service_name}:latest'

# Build options
options:
  machineType: '${machine_type}'
  diskSizeGb: ${disk_size}
  logging: CLOUD_LOGGING_ONLY

# Total timeout
timeout: '${build_timeout}'

# Tags for organization
tags:
  - '${service_name}'
  - '${environment}'
  - 'june-ai-platform'

# Substitutions
substitutions:
  _SERVICE_NAME: '${service_name}'
  _ENVIRONMENT: '${environment}'
